// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dataTree.sql

package db

import (
	"context"
)

const getTreesByLocation = `-- name: GetTreesByLocation :many
SELECT id, species, height, latitude, longitude, diameter, age, health, status, created_at
FROM dataTree
WHERE latitude BETWEEN $1 AND $2
  AND longitude BETWEEN $3 AND $4
`

type GetTreesByLocationParams struct {
	Latitude    float64
	Latitude_2  float64
	Longitude   float64
	Longitude_2 float64
}

func (q *Queries) GetTreesByLocation(ctx context.Context, arg GetTreesByLocationParams) ([]Datatree, error) {
	rows, err := q.db.QueryContext(ctx, getTreesByLocation,
		arg.Latitude,
		arg.Latitude_2,
		arg.Longitude,
		arg.Longitude_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datatree
	for rows.Next() {
		var i Datatree
		if err := rows.Scan(
			&i.ID,
			&i.Species,
			&i.Height,
			&i.Latitude,
			&i.Longitude,
			&i.Diameter,
			&i.Age,
			&i.Health,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTreesFromDatabase = `-- name: ListTreesFromDatabase :many
SELECT id, species, height, latitude, longitude, diameter, age, health, status, created_at FROM dataTree
ORDER BY created_at DESC
`

func (q *Queries) ListTreesFromDatabase(ctx context.Context) ([]Datatree, error) {
	rows, err := q.db.QueryContext(ctx, listTreesFromDatabase)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datatree
	for rows.Next() {
		var i Datatree
		if err := rows.Scan(
			&i.ID,
			&i.Species,
			&i.Height,
			&i.Latitude,
			&i.Longitude,
			&i.Diameter,
			&i.Age,
			&i.Health,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
