// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type RiskAssessment struct {
	ID           int64
	TreeID       int32
	Score        int32
	Level        string
	CalculatedAt time.Time
}

type Tree struct {
	ID        int64
	Latitude  float64
	Longitude float64
	Species   sql.NullString
	Height    sql.NullFloat64
	Diameter  sql.NullFloat64
	Age       sql.NullInt32
	Health    sql.NullString
	Status    sql.NullString
	CreatedAt sql.NullTime
}

type WeatherEvent struct {
	ID         int64
	Region     string
	WindSpeed  float64
	RainfallMm sql.NullFloat64
	Severity   string
	OccurredAt time.Time
	CreatedAt  time.Time
}
