// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: riskAssesment.sql

package db

import (
	"context"
	"database/sql"
)

const createRiskAssessment = `-- name: CreateRiskAssessment :one
INSERT INTO risk_assessments (
    tree_id,
    score,
    level,
    calculated_at
) VALUES (
             $1, $2, $3, now()
         )
RETURNING id, tree_id, score, level, calculated_at
`

type CreateRiskAssessmentParams struct {
	TreeID int32
	Score  int32
	Level  string
}

func (q *Queries) CreateRiskAssessment(ctx context.Context, arg CreateRiskAssessmentParams) (RiskAssessment, error) {
	row := q.db.QueryRowContext(ctx, createRiskAssessment, arg.TreeID, arg.Score, arg.Level)
	var i RiskAssessment
	err := row.Scan(
		&i.ID,
		&i.TreeID,
		&i.Score,
		&i.Level,
		&i.CalculatedAt,
	)
	return i, err
}

const getLatestRiskByTree = `-- name: GetLatestRiskByTree :one
SELECT id, tree_id, score, level, calculated_at
FROM risk_assessments
WHERE tree_id = $1
ORDER BY calculated_at DESC
LIMIT 1
`

func (q *Queries) GetLatestRiskByTree(ctx context.Context, treeID int32) (RiskAssessment, error) {
	row := q.db.QueryRowContext(ctx, getLatestRiskByTree, treeID)
	var i RiskAssessment
	err := row.Scan(
		&i.ID,
		&i.TreeID,
		&i.Score,
		&i.Level,
		&i.CalculatedAt,
	)
	return i, err
}

const getRiskByID = `-- name: GetRiskByID :one
SELECT id, tree_id, score, level, calculated_at
FROM risk_assessments
WHERE id = $1
`

func (q *Queries) GetRiskByID(ctx context.Context, id int64) (RiskAssessment, error) {
	row := q.db.QueryRowContext(ctx, getRiskByID, id)
	var i RiskAssessment
	err := row.Scan(
		&i.ID,
		&i.TreeID,
		&i.Score,
		&i.Level,
		&i.CalculatedAt,
	)
	return i, err
}

const listHighRiskTrees = `-- name: ListHighRiskTrees :many
SELECT t.id, t.latitude, t.longitude, t.species, t.height, t.diameter, t.age, t.health, t.status, t.created_at, r.score, r.level
FROM trees t
         JOIN risk_assessments r ON r.tree_id = t.id
WHERE r.level = 'high'
  AND r.calculated_at = (
    SELECT MAX(r2.calculated_at)
    FROM risk_assessments r2
    WHERE r2.tree_id = t.id
)
`

type ListHighRiskTreesRow struct {
	ID        int64
	Latitude  float64
	Longitude float64
	Species   sql.NullString
	Height    sql.NullFloat64
	Diameter  sql.NullFloat64
	Age       sql.NullInt32
	Health    sql.NullString
	Status    sql.NullString
	CreatedAt sql.NullTime
	Score     int32
	Level     string
}

func (q *Queries) ListHighRiskTrees(ctx context.Context, id int32) ([]ListHighRiskTreesRow, error) {
	rows, err := q.db.QueryContext(ctx, listHighRiskTrees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHighRiskTreesRow
	for rows.Next() {
		var i ListHighRiskTreesRow
		if err := rows.Scan(
			&i.ID,
			&i.Latitude,
			&i.Longitude,
			&i.Species,
			&i.Height,
			&i.Diameter,
			&i.Age,
			&i.Health,
			&i.Status,
			&i.CreatedAt,
			&i.Score,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediumOrHighRiskTrees = `-- name: ListMediumOrHighRiskTrees :many
SELECT t.id, t.latitude, t.longitude, t.species, t.height, t.diameter, t.age, t.health, t.status, t.created_at, r.score, r.level
FROM trees t
         JOIN risk_assessments r ON r.tree_id = t.id
WHERE r.level IN ('medium', 'high')
  AND r.calculated_at = (
    SELECT MAX(r2.calculated_at)
    FROM risk_assessments r2
    WHERE r2.tree_id = t.id
)
`

type ListMediumOrHighRiskTreesRow struct {
	ID        int64
	Latitude  float64
	Longitude float64
	Species   sql.NullString
	Height    sql.NullFloat64
	Diameter  sql.NullFloat64
	Age       sql.NullInt32
	Health    sql.NullString
	Status    sql.NullString
	CreatedAt sql.NullTime
	Score     int32
	Level     string
}

func (q *Queries) ListMediumOrHighRiskTrees(ctx context.Context, id int32) ([]ListMediumOrHighRiskTreesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMediumOrHighRiskTrees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMediumOrHighRiskTreesRow
	for rows.Next() {
		var i ListMediumOrHighRiskTreesRow
		if err := rows.Scan(
			&i.ID,
			&i.Latitude,
			&i.Longitude,
			&i.Species,
			&i.Height,
			&i.Diameter,
			&i.Age,
			&i.Health,
			&i.Status,
			&i.CreatedAt,
			&i.Score,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiskByTree = `-- name: ListRiskByTree :many
SELECT id, tree_id, score, level, calculated_at
FROM risk_assessments
WHERE tree_id = $1
ORDER BY calculated_at DESC
`

func (q *Queries) ListRiskByTree(ctx context.Context, treeID int32) ([]RiskAssessment, error) {
	rows, err := q.db.QueryContext(ctx, listRiskByTree, treeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RiskAssessment
	for rows.Next() {
		var i RiskAssessment
		if err := rows.Scan(
			&i.ID,
			&i.TreeID,
			&i.Score,
			&i.Level,
			&i.CalculatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
