// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tree.sql

package db

import (
	"context"
	"database/sql"
)

const createTree = `-- name: CreateTree :one
INSERT INTO trees (
    latitude,
    longitude,
    species,
    height,
    diameter,
    age,
    health
) VALUES (
             $1, $2, $3, $4, $5, $6, $7
         )
RETURNING id, latitude, longitude, species, height, diameter, age, health, status, created_at
`

type CreateTreeParams struct {
	Latitude  float64
	Longitude float64
	Species   sql.NullString
	Height    sql.NullFloat64
	Diameter  sql.NullFloat64
	Age       sql.NullInt32
	Health    sql.NullString
}

func (q *Queries) CreateTree(ctx context.Context, arg CreateTreeParams) (Tree, error) {
	row := q.db.QueryRowContext(ctx, createTree,
		arg.Latitude,
		arg.Longitude,
		arg.Species,
		arg.Height,
		arg.Diameter,
		arg.Age,
		arg.Health,
	)
	var i Tree
	err := row.Scan(
		&i.ID,
		&i.Latitude,
		&i.Longitude,
		&i.Species,
		&i.Height,
		&i.Diameter,
		&i.Age,
		&i.Health,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTree = `-- name: DeleteTree :exec
DELETE FROM trees
WHERE id = $1
`

func (q *Queries) DeleteTree(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTree, id)
	return err
}

const getTreeByID = `-- name: GetTreeByID :one
SELECT id, latitude, longitude, species, height, diameter, age, health, status, created_at
FROM trees
WHERE id = $1
`

func (q *Queries) GetTreeByID(ctx context.Context, id int64) (Tree, error) {
	row := q.db.QueryRowContext(ctx, getTreeByID, id)
	var i Tree
	err := row.Scan(
		&i.ID,
		&i.Latitude,
		&i.Longitude,
		&i.Species,
		&i.Height,
		&i.Diameter,
		&i.Age,
		&i.Health,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPotentialRiskTrees = `-- name: ListPotentialRiskTrees :many
SELECT id, latitude, longitude, species, height, diameter, age, health, status, created_at
FROM trees
WHERE
    age > 20
   OR height > 10
   OR health IN ('poor', 'critical')
`

func (q *Queries) ListPotentialRiskTrees(ctx context.Context) ([]Tree, error) {
	rows, err := q.db.QueryContext(ctx, listPotentialRiskTrees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tree
	for rows.Next() {
		var i Tree
		if err := rows.Scan(
			&i.ID,
			&i.Latitude,
			&i.Longitude,
			&i.Species,
			&i.Height,
			&i.Diameter,
			&i.Age,
			&i.Health,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrees = `-- name: ListTrees :many
SELECT id, latitude, longitude, species, height, diameter, age, health, status, created_at
FROM trees
ORDER BY created_at DESC
`

func (q *Queries) ListTrees(ctx context.Context) ([]Tree, error) {
	rows, err := q.db.QueryContext(ctx, listTrees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tree
	for rows.Next() {
		var i Tree
		if err := rows.Scan(
			&i.ID,
			&i.Latitude,
			&i.Longitude,
			&i.Species,
			&i.Height,
			&i.Diameter,
			&i.Age,
			&i.Health,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTreesByBoundingBox = `-- name: ListTreesByBoundingBox :many
SELECT id, latitude, longitude, species, height, diameter, age, health, status, created_at
FROM trees
WHERE latitude BETWEEN $1 AND $2
  AND longitude BETWEEN $3 AND $4
`

type ListTreesByBoundingBoxParams struct {
	Latitude    float64
	Latitude_2  float64
	Longitude   float64
	Longitude_2 float64
}

func (q *Queries) ListTreesByBoundingBox(ctx context.Context, arg ListTreesByBoundingBoxParams) ([]Tree, error) {
	rows, err := q.db.QueryContext(ctx, listTreesByBoundingBox,
		arg.Latitude,
		arg.Latitude_2,
		arg.Longitude,
		arg.Longitude_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tree
	for rows.Next() {
		var i Tree
		if err := rows.Scan(
			&i.ID,
			&i.Latitude,
			&i.Longitude,
			&i.Species,
			&i.Height,
			&i.Diameter,
			&i.Age,
			&i.Health,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTree = `-- name: UpdateTree :one
UPDATE trees
SET
    latitude   = $1,
    longitude  = $2,
    species    = $3,
    height     = $4,
    diameter   = $5,
    age        = $6,
    health     = $7
WHERE id = $8
RETURNING id, latitude, longitude, species, height, diameter, age, health, status, created_at
`

type UpdateTreeParams struct {
	Latitude  float64
	Longitude float64
	Species   sql.NullString
	Height    sql.NullFloat64
	Diameter  sql.NullFloat64
	Age       sql.NullInt32
	Health    sql.NullString
	ID        int64
}

func (q *Queries) UpdateTree(ctx context.Context, arg UpdateTreeParams) (Tree, error) {
	row := q.db.QueryRowContext(ctx, updateTree,
		arg.Latitude,
		arg.Longitude,
		arg.Species,
		arg.Height,
		arg.Diameter,
		arg.Age,
		arg.Health,
		arg.ID,
	)
	var i Tree
	err := row.Scan(
		&i.ID,
		&i.Latitude,
		&i.Longitude,
		&i.Species,
		&i.Height,
		&i.Diameter,
		&i.Age,
		&i.Health,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
