// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weatherEvents.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createWeatherEvent = `-- name: CreateWeatherEvent :one
INSERT INTO weather_events (
    region,
    wind_speed,
    rainfall_mm,
    severity,
    occurred_at
) VALUES (
             $1, $2, $3, $4, $5
         )
RETURNING id, region, wind_speed, rainfall_mm, severity, occurred_at, created_at
`

type CreateWeatherEventParams struct {
	Region     string
	WindSpeed  float64
	RainfallMm sql.NullFloat64
	Severity   string
	OccurredAt time.Time
}

func (q *Queries) CreateWeatherEvent(ctx context.Context, arg CreateWeatherEventParams) (WeatherEvent, error) {
	row := q.db.QueryRowContext(ctx, createWeatherEvent,
		arg.Region,
		arg.WindSpeed,
		arg.RainfallMm,
		arg.Severity,
		arg.OccurredAt,
	)
	var i WeatherEvent
	err := row.Scan(
		&i.ID,
		&i.Region,
		&i.WindSpeed,
		&i.RainfallMm,
		&i.Severity,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSevereWeatherByRegion = `-- name: GetLatestSevereWeatherByRegion :one
SELECT id, region, wind_speed, rainfall_mm, severity, occurred_at, created_at
FROM weather_events
WHERE region = $1
  AND severity = 'high'
ORDER BY occurred_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSevereWeatherByRegion(ctx context.Context, region string) (WeatherEvent, error) {
	row := q.db.QueryRowContext(ctx, getLatestSevereWeatherByRegion, region)
	var i WeatherEvent
	err := row.Scan(
		&i.ID,
		&i.Region,
		&i.WindSpeed,
		&i.RainfallMm,
		&i.Severity,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWeatherEventByID = `-- name: GetWeatherEventByID :one
SELECT id, region, wind_speed, rainfall_mm, severity, occurred_at, created_at
FROM weather_events
WHERE id = $1
`

func (q *Queries) GetWeatherEventByID(ctx context.Context, id int64) (WeatherEvent, error) {
	row := q.db.QueryRowContext(ctx, getWeatherEventByID, id)
	var i WeatherEvent
	err := row.Scan(
		&i.ID,
		&i.Region,
		&i.WindSpeed,
		&i.RainfallMm,
		&i.Severity,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listHeavyRainEvents = `-- name: ListHeavyRainEvents :many
SELECT id, region, wind_speed, rainfall_mm, severity, occurred_at, created_at
FROM weather_events
WHERE rainfall_mm >= $1
ORDER BY occurred_at DESC
`

func (q *Queries) ListHeavyRainEvents(ctx context.Context, rainfallMm sql.NullFloat64) ([]WeatherEvent, error) {
	rows, err := q.db.QueryContext(ctx, listHeavyRainEvents, rainfallMm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeatherEvent
	for rows.Next() {
		var i WeatherEvent
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.WindSpeed,
			&i.RainfallMm,
			&i.Severity,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHighWindEvents = `-- name: ListHighWindEvents :many
SELECT id, region, wind_speed, rainfall_mm, severity, occurred_at, created_at
FROM weather_events
WHERE wind_speed >= $1
ORDER BY occurred_at DESC
`

func (q *Queries) ListHighWindEvents(ctx context.Context, windSpeed float64) ([]WeatherEvent, error) {
	rows, err := q.db.QueryContext(ctx, listHighWindEvents, windSpeed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeatherEvent
	for rows.Next() {
		var i WeatherEvent
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.WindSpeed,
			&i.RainfallMm,
			&i.Severity,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentWeatherEvents = `-- name: ListRecentWeatherEvents :many
SELECT id, region, wind_speed, rainfall_mm, severity, occurred_at, created_at
FROM weather_events
WHERE occurred_at >= now() - INTERVAL '24 hours'
ORDER BY occurred_at DESC
`

func (q *Queries) ListRecentWeatherEvents(ctx context.Context) ([]WeatherEvent, error) {
	rows, err := q.db.QueryContext(ctx, listRecentWeatherEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeatherEvent
	for rows.Next() {
		var i WeatherEvent
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.WindSpeed,
			&i.RainfallMm,
			&i.Severity,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSevereWeatherEvents = `-- name: ListSevereWeatherEvents :many
SELECT id, region, wind_speed, rainfall_mm, severity, occurred_at, created_at
FROM weather_events
WHERE severity = 'high'
ORDER BY occurred_at DESC
`

func (q *Queries) ListSevereWeatherEvents(ctx context.Context) ([]WeatherEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSevereWeatherEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeatherEvent
	for rows.Next() {
		var i WeatherEvent
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.WindSpeed,
			&i.RainfallMm,
			&i.Severity,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeatherEvents = `-- name: ListWeatherEvents :many
SELECT id, region, wind_speed, rainfall_mm, severity, occurred_at, created_at
FROM weather_events
ORDER BY occurred_at DESC
`

func (q *Queries) ListWeatherEvents(ctx context.Context) ([]WeatherEvent, error) {
	rows, err := q.db.QueryContext(ctx, listWeatherEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeatherEvent
	for rows.Next() {
		var i WeatherEvent
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.WindSpeed,
			&i.RainfallMm,
			&i.Severity,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeatherEventsByRegion = `-- name: ListWeatherEventsByRegion :many
SELECT id, region, wind_speed, rainfall_mm, severity, occurred_at, created_at
FROM weather_events
WHERE region = $1
ORDER BY occurred_at DESC
`

func (q *Queries) ListWeatherEventsByRegion(ctx context.Context, region string) ([]WeatherEvent, error) {
	rows, err := q.db.QueryContext(ctx, listWeatherEventsByRegion, region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeatherEvent
	for rows.Next() {
		var i WeatherEvent
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.WindSpeed,
			&i.RainfallMm,
			&i.Severity,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
